CAPROVER_VERSION=1.15.4
CAPROVER_IMAGE_NAME=caprover/caprover
EDGE_IMAGE_NAME=caprover/caprover-edge
EDGE_VERSION=0.0.1
FRONTEND_REPOSITORY=https://github.com/githubsaturn/caprover-frontend.git
RELEASE_FRONTEND_COMMIT=c9005cc2e5ac1b6816cb983d2d3732338c546a94
EDGE_FRONTEND_COMMIT=
