name: Run build

on:
    workflow_dispatch:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
            - release

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v5
              with:
                  node-version: 24
            - run: |
                  sudo bash -c "mkdir /captain && chown -R `whoami` /captain"
                  npm ci 
                  npm run build 
                  npm run test
