name: Run build

on:
    workflow_dispatch:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
            - release

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
            - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
              with:
                  node-version: 24
            - run: |
                  sudo bash -c "mkdir /captain && chown -R `whoami` /captain"
                  npm ci 
                  npm run build 
                  npm run test
